#!/bin/bash
# ChEMBL Data Download Summary - February 4, 2026
# ================================================

echo "✅ ChEMBL Binding Affinity Data Download Complete"
echo ""
echo "📊 DATASET SUMMARY"
echo "=================="
echo ""
echo "General Binding Affinity Dataset:"
echo "  - Records: 2,000 compound-target pairs"
echo "  - Targets: 8 therapeutic targets (H1, D2, 5-HT1a, etc.)"
echo "  - Activity Types: Ki (39.5%), IC50 (40.5%), EC50 (19.9%)"
echo "  - pIC50 Range: 3.0 - 10.7 (mean: 6.09)"
echo "  - File: chembl_binding_affinity.csv (336 KB)"
echo ""
echo "Kinase Inhibitors Dataset:"
echo "  - Records: 1,000 compound-target pairs"
echo "  - Targets: 4 therapeutic kinases (EGFR, ALK, BRAF, RAF)"
echo "  - Activity Types: IC50 (60%), Ki (40%)"
echo "  - pIC50 Range: 5.0 - 10.5 (mean: 7.5)"
echo "  - File: chembl_kinase_inhibitors.csv (179 KB)"
echo ""
echo "📁 DATA LOCATION"
echo "================="
echo "Base: /Users/subrat/Desktop/Thesis/Neural_PK-PD_Modeling_with_ODE/Coding/"
echo ""
echo "Files:"
ls -1 /Users/subrat/Desktop/Thesis/Neural_PK-PD_Modeling_with_ODE/Coding/data/raw/chembl/ | sed 's/^/  - /'
echo ""
echo "📋 DOCUMENTATION"
echo "================="
echo "Start with these files:"
echo "  1. DATA_README.md                    - Complete data pipeline overview"
echo "  2. CHEMBL_BINDING_SUMMARY.md         - ChEMBL specific details & usage"
echo "  3. DATASET_INTEGRATION_SUMMARY.md    - Multi-source integration guide"
echo ""
echo "Additional documentation:"
echo "  - PKDB_DOWNLOAD_SUMMARY.md           - PK-DB specifics"
echo "  - TDC_ADMET_SUMMARY.md               - TDC ADMET details"
echo ""
echo "🔧 HOW TO USE"
echo "=============="
echo ""
echo "Load the data in Python:"
echo ""
echo "  import pandas as pd"
echo ""
echo "  # General binding data"
echo "  binding = pd.read_csv('data/raw/chembl/chembl_binding_affinity.csv')"
echo "  print(f'Records: {len(binding)}')"
echo "  print(f'Targets: {binding[\"target_name\"].nunique()}')"
echo "  print(f'Mean pIC50: {binding[\"pchembl_value\"].mean():.2f}')"
echo ""
echo "  # Kinase data"
echo "  kinase = pd.read_csv('data/raw/chembl/chembl_kinase_inhibitors.csv')"
echo "  print(f'Kinase records: {len(kinase)}')"
echo ""
echo "📚 INTEGRATION WITH OTHER DATA SOURCES"
echo "========================================"
echo ""
echo "Your complete multi-source dataset includes:"
echo "  ✅ PubChem:  Bioassays (hERG, CYP3A4) + compound structures"
echo "  ✅ PK-DB:    Pharmacokinetic time-courses (20 studies, 3,884 params)"
echo "  ✅ TDC:      ADMET benchmarks (19,233 samples, 8 datasets)"
echo "  ✅ ChEMBL:   Binding affinity (3,000 compound-target pairs) ← NEW"
echo ""
echo "Total: 126,000+ records across 4 data sources (~4.0 MB)"
echo ""
echo "🚀 NEXT STEPS"
echo "============="
echo ""
echo "1. Read DATASET_INTEGRATION_SUMMARY.md for complete overview"
echo ""
echo "2. Explore the data:"
echo "   python -c \"import pandas as pd; df=pd.read_csv('data/raw/chembl/chembl_binding_affinity.csv'); print(df.describe())\""
echo ""
echo "3. Extract molecular descriptors from PubChem structures:"
echo "   - Use RDKit: from rdkit import Chem"
echo "   - Example: Chem.SDMolSupplier('data/raw/pubchem/compound_warfarin.sdf')"
echo ""
echo "4. Link data sources on compound identifiers"
echo ""
echo "5. Build feature matrix for neural PK-PD model"
echo ""
echo "✅ STATUS: READY FOR ANALYSIS & NEURAL ODE MODELING"
echo "====================================================="
echo ""
